## Intro

I'm prospecting this tutorial to be fun and straight forward. No jargon will be entertained / practiced without prior and proper explanation. But I think it would be up-and-coming if the reader has basic knowledge in Linear Algebra and Python.

Let's begin with importing tensorflow library, shall we ? 

[Installation of tensorflow](https://www.tensorflow.org/install/) 

In [1]:
import tensorflow as tf

## What is TensorFlow and how it works ?

TensorFlow is an open source software library for numerical computation, originally developed by researchers and engineers working on the Google Brain Team within Google's Machine Intelligence research organization. The flexible architecture of TensorFlow allows us to deploy computation to one or more CPUs or GPUs in a desktop, server, or mobile device with a single API.

What is this flexible architecture worth talking about?  

Every computation performed using Tensorflow will be done in a two-steps structure:

1. Define a computation graph 
    - Contains a series of operations (```ops```)
    - Operations could be simple mathematical operations to complex numerical optimization techniques.
2. Launch a Session for executing the graph 
    - Translates and passes the ops represented in graphs to the computation devices eg. GPU

Too much new terms right? `Session` , `Graph` ... Don't worry, we'll cover all of it in detail :D

Let's begin with operations in TensorFlow. 

As we introduced above, an operation could be anything. Addition, multiplication, calculating gradients ... Even the declaration of operands, e.g. Variables, are also operations in that sense. 

We'll begin with `source operations` in `tf` and then elaborate the ideas of `tensors, graph, session, variables and placeholders` as we go on.

#### Source operations

- Operations which can be used to pass information to other operations 
- Usually they don't take any input. 
    - Eg. tf.constant( [ ] )

In [2]:
a = tf.constant([[2]])
print(a)

Tensor("Const:0", shape=(1, 1), dtype=int32)


You might be thinking why we're using a `source operation` in tf?   

Simple answer is, we define `tensors` with them as you've seen just now. Now, the next obvious question is what is a `tensor`? 

We'll talk details about tensor in a moment. But, as of now, consider a `tensor` as more or less like an n-dimensional array. It has a shape, a data type and a value.

Usually, when we define a variable or a constant in Python, immediately we get that value stored into that variable. Here comes the two-step procedure for computation in TensorFlow. As mentioned earlier, in `tf` just definition of an operation is not enough. Because it's just a computational graph and no value is asserted to it. If we need to load value into it, then a Session should be launched to execute that graph. Let's do that.

In [46]:
sess = tf.Session()
print(sess.run(a))

[[2]]


Aha!! We've a value now for `a`. It's 2. Now you see the shape of the tensor. It is (1,1). What does it mean? Let's try more examples to learn it yourself.

In [15]:
sess = tf.Session()
a = tf.constant([2])
print("\nTensor definition: ", a)
print("Value on session:")
print(sess.run(a))
a = tf.constant([[2]])
print("\nTensor definition: ", a)
print("Value on session:")
print(sess.run(a))
a = tf.constant([[2], [1]])
print("\nTensor definition: ", a)
print("Value on session:")
print(sess.run(a))
a = tf.constant([[2, 1]])
print("\nTensor definition: ", a)
print("Value on session:")
print(sess.run(a))
a = tf.constant([[2, 1], [3, 4]])
print("\nTensor definition: ", a)
print("Value on session:")
print(sess.run(a))


Tensor definition:  Tensor("Const_13:0", shape=(1,), dtype=int32)
Value on session:
[2]

Tensor definition:  Tensor("Const_14:0", shape=(1, 1), dtype=int32)
Value on session:
[[2]]

Tensor definition:  Tensor("Const_15:0", shape=(2, 1), dtype=int32)
Value on session:
[[2]
 [1]]

Tensor definition:  Tensor("Const_16:0", shape=(1, 2), dtype=int32)
Value on session:
[[2 1]]

Tensor definition:  Tensor("Const_17:0", shape=(2, 2), dtype=int32)
Value on session:
[[2 1]
 [3 4]]


You got it right. A shape is actually the dimensions of that tensor. `No. of rows x No. of columns`

Note that in first example, we are not specifying no. of columns and shape is displaying it accordingly.   

`dtype` tells us about the data type of the variable and it is `int32`. 

Now let's perform an simple addition in tf. 


In [47]:
a = tf.constant([[2]])
b = tf.constant([[3]])
c = tf.add(a, b)
print("Tensor c: ", c)
sess = tf.Session()
print("Value of c: ", sess.run(c))
sess.close()

Tensor c:  Tensor("Add_2:0", shape=(1, 1), dtype=int32)
Value of c:  [[5]]


## Computational graph  

Let's discuss the Computational Graph we've just created for the sum operation.
A computational graph consists of two parts

1. `Edges` which are `tensors`.
    - We have two `edges` here.
        - a and b
    - Through `edges` the `operations` are communicated.
2. `Nodes` which are operations.
    - tf.add( ) and definitions of a and b. 

Can you imagine how our graph would look like ?  

![Alt Text](https://media.licdn.com/mpr/mpr/AAEAAQAAAAAAAAkjAAAAJDgzYTUxMGI3LTZjYTctNDliNi1hMDQ3LWU3YzNlYTE3ODU4Zg.png)

This is a simple graph demonstrated for sum operation. But graphs get really complicated when we scale up. The graph below is used for a simple image classification problem using [Convolutional Neural Nets](http://cs231n.github.io/convolutional-networks/).

![Alt Text](https://renatocunha.com/img/dlnd-image-classification/main-graph.png)


I didn't bring up this graph to spread panic :D I wanted to give an idea about how a real problem is solved using Tensorflow. Afterall, Tensorflow is not made for performing trifle sums. We may use [Tensorboard](https://www.tensorflow.org/get_started/summaries_and_tensorboard) to visualize the computation graph.

Now let's get into the detailed understanding of tensors.

## Tensors 

Tensor has a latin origin with a simple meaning, `that which strecthes`. 
Tensor is a mathematical object that was originally used to analyze the way materials stretch under pressure. But nowadays we treat tensors as multidimensional arrays. 

Wait a sec. We need to talk about dimensions in Physics before we start reading Gospel of Tensors. :D

Consider the following. 

![Alt Text](https://ibm.box.com/shared/static/ymn0hl3hf8s3xb4k15v22y5vmuodnue1.svg)

- Zero dimension :- A point [A scalar]
- One dimension :- A line [1-D array]
- Two dimension :- A surface [2-D array]
- Three dimension :- A volume [3-D array]
- What about a four dimensional space ??
    - It is bit difficult to visualize a 4-D space.
    - Scientists call it a hyperspace or spacetime (4th axis being time).
    - Maybe be we can think of a **volume changing in time** as a 4-D vector. 
    - It is complicated like some relationships. :P


In [3]:
scalar = tf.constant([2])
vector = tf.constant([2, 3, 4])
matrix = tf.constant([[2, 3, 4], [5, 6, 7], [8, 9, 10]])
tensor = tf.constant([[[1,2,3], [5, 6, 7], [8, 9, 10]], 
                      [[3, 2, 1], [1, 10, 11], [6, 5 ,7]], 
                      [[9, 7 , 6], [18, 4, 3], [7, 5, 4]]])

with tf.Session() as sess:
    print("\nScalar: \n", sess.run(scalar))
    print("\nVector: \n", sess.run(vector))
    print("\nMatrix: \n", sess.run(matrix))
    print("\nTensor: \n", sess.run(tensor))


Scalar: 
 [2]

Vector: 
 [2 3 4]

Matrix: 
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

Tensor: 
 [[[ 1  2  3]
  [ 5  6  7]
  [ 8  9 10]]

 [[ 3  2  1]
  [ 1 10 11]
  [ 6  5  7]]

 [[ 9  7  6]
  [18  4  3]
  [ 7  5  4]]]


## Why Tensors ?
    
A Tensor gives a lot of freedom when it comes to structuring the dataset the way we would like to. No, I' m not making this up. Let's consider the example of an image. 

An image is represented digitally as pixels and each pixel is represented by a number called `pixel value`. 

For example a grayscale image, the pixel value is a single number that represents the brightness of the pixel. The most common  pixel format is the byte image, where this number is stored as an 8-bit integer giving a range of possible values from 0 to 255 (2^8). Typically zero is taken to be black, and 255 is taken to be white. Values in between make up the different shades of gray.

![Alt Text](https://ibm.box.com/shared/static/xlpv9h5xws248c09k1rlx7cer69y4grh.png)

To represent color images, separate red, green and blue components must be specified for each pixel (assuming an RGB colorspace), and so the `pixel value` is actually a vector of three numbers. Often the three different components are stored as three separate grayscale images known as color planes (one for each of red, green and blue), which have to be recombined when displaying or processing.

Now an RGB image will be represented as a tensor as three 3 x 3 matrices stacked as we've seen above. 

Taking it forward, why don't we perform some matrix operations with **`tf`**, shall we? 

In [5]:
matrix_a = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_b = tf.constant([[3, 2, 3], [4, 5, 0], [7, 6, 9]])

mat_sum = tf.add(matrix_a, matrix_b)
mat_pro = tf.matmul(matrix_a, matrix_b)
mat_pro_elem = tf.multiply(matrix_a, matrix_b)

with tf.Session() as sess:
    print("\nMatrix addition \n")
    print(sess.run(mat_sum))
    print("\nMatrix multiplication \n")
    print(sess.run(mat_pro))
    print("\nElementwise matrix multiplication\n")
    print(sess.run(mat_pro_elem))


Matrix addition 

[[ 4  4  6]
 [ 8 10  6]
 [14 14 18]]

Matrix multiplication 

[[ 32  30  30]
 [ 74  69  66]
 [116 108 102]]

Elementwise matrix multiplication

[[ 3  4  9]
 [16 25  0]
 [49 48 81]]


## More power to `tf` : Variables

- We can define a variable in a computation graph using **`tf.Variable()`** but that's not enough unlike `source operations`. 
- To deploy them in a `session` we should initialize all the defined variables before running the session. 
- **`tf.global_variables_initializer`** can do this job for us. 

Note:  
Variables save a value during and after the calculations are executed which means there's no change in the value stored. This idea is really important when we understand `placeholders` after sometime.

Let's implement a simple counter using what we know yet. 

In [10]:
# Graph
state = tf.Variable(0) # define a variable
step = tf.constant(1) # define a unit step
new_value = tf.add(state, step) # define an operation 
update = tf.assign(state, new_value) # update the value of state to new_value using tf.assign()

# Session
with tf.Session() as sess:
    print(sess.run(update))

Running the above code, **`tf`** will gift you a `FailedPreconditionError: Attempting to use uninitialized value Variable_2` error.   

What is wrong here?   
Attempting to use an uninitialized value is the crime we've committed here it says. So far we played around with `tf.constant()` but now a `tf.Variable()` is in the scene and it's going to make a difference. We'll be needing the initialization all the variables before using them in a **`tf.session()`**. This is called lazy evaluation, which means, evaluation of our variables/graph happens only at a session.

In [11]:
# Graph
state = tf.Variable(0) # define a variable
step = tf.constant(1) # define a unit step
new_value = tf.add(state, step) # define an operation 
update = tf.assign(state, new_value) # update the value of state to new_value using tf.assign()

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(update))

1


Woo-Hoo !! It works now. But you may think that, for implementing a simple counter, why do we need to go through all these procedures. Well, plucking a nail from the wall using an excavator would fit a good example to this situation. As we said earlier, `tf` is not meant to do trifle computations and as things scale up, we'll be more procedural and cautious.  



## Placeholders

Placeholders are say, variables itself, but won't receive a value until a later point or runtime. What do we mean by that ? 

In [56]:
sample = tf.placeholder(tf.int8)
op = tf.multiply(sample, 10)
print("Placeholder : ", sample)
with tf.Session() as sess:
    print(sess.run(op))

If you run the above code, you'll be confronting an `InvalidArgumentError`. Why?  

Because the placeholder is not fed by any value. It's an empty space with a datatype.   

We can compare placeholder with a reserving a hotel room. 

 - room_221B = marriot.reservation ( male )
 
Here, we're expecting a person of type `male` to fill that reservation at room number `221B` during the check-in at `Marriot` hotel. Until then, the room is empty.  

Similarly,  

- sample = tf.placeholder ( tf.int8 )

We're expecting a data of type `tf.int8` to fill that empty space **`sample`** during the `session`. This is really important, as it enables us to feed data to a TensorFlow model from outside a model. 

To pass the data to the model we call the session with an extra argument `feed_dict` in which we should pass a dictionary with each placeholder name folowed by its respective data.

In [14]:
sample = tf.placeholder(tf.int8, (3,))
op = tf.multiply(sample, 10)
print("Placeholder : ", sample)
dictionary = {sample: [2, 3, 4]}
with tf.Session() as sess:
    print(sess.run(op, feed_dict=dictionary))

Placeholder :  Tensor("Placeholder_2:0", shape=(3,), dtype=int8)
[20 30 40]


So what are these placeholders and what do they do?   
- Placeholders can be seen as "holes" in your model, "holes" which you will pass the data to. 
- We can create them using `tf.placeholder (datatype, shape)` 
- Datatype specifies the type of data (integers, floating points, strings, booleans) along with its precision (8, 16, 32, 64) bits. 
- Shape of the expected array can also be initialized during the intialization of a placeholder along with the datatype. It is optional. 

There is a detailed table given above regarding the various datatypes. The definition of each data type with the respective python syntax is defined as:  

|Data type	|Python type|Description|
| --------- | --------- | --------- |
|DT_FLOAT	|tf.float32	|32 bits floating point.|
|DT_DOUBLE	|tf.float64	|64 bits floating point.|
|DT_INT8	|tf.int8	|8 bits signed integer.|
|DT_INT16	|tf.int16	|16 bits signed integer.|
|DT_INT32	|tf.int32	|32 bits signed integer.|
|DT_INT64	|tf.int64	|64 bits signed integer.|
|DT_UINT8	|tf.uint8	|8 bits unsigned integer.|
|DT_STRING	|tf.string	|Variable length byte arrays. Each element of a Tensor is a byte array.|
|DT_BOOL	|tf.bool	|Boolean.|
|DT_COMPLEX64	|tf.complex64	|Complex number made of two 32 bits floating points: real and imaginary parts.|
|DT_COMPLEX128	|tf.complex128	|Complex number made of two 64 bits floating points: real and imaginary parts.|
|DT_QINT8	|tf.qint8	|8 bits signed integer used in quantized Ops.|
|DT_QINT32	|tf.qint32	|32 bits signed integer used in quantized Ops.|
|DT_QUINT8	|tf.quint8	|8 bits unsigned integer used in quantized Ops.
Starting from `sourcing operations`, we reached `placeholders` as expected. We'll discuss `operations` breifly and end this introductory tutorial. 

## Operations

Operations are nodes that represent the mathematical operations over the tensors on a graph. These are like functions in python but operate directly over tensors and each one does a specific thing.

Eg. tf.matmul, tf.add, tf.nn.sigmoid, tf.nn.relu

NB : tf.nn.sigmoid and tf.nn.relu are activiation functions, which needs more explanation. Chuck it for now. 

So let's build a graph using all the concepts we've learned yet, right? 

Consider the following equation, $$ y = Wx + b $$ 

We need to evaluate values of $y$ for different $x$ keeping $W$ and $b$ as constant. 

Let's break down the graph.  

- Here we've two operations, a sum and a multiplication. So, there would be two nodes in our graph. 
- We need to define two variables i.e. $W$ and $b$
- We need to define one placeholder for $x$ and feed the value of $x$ each time the graph is executed in a session.

So our graph would be, 

![Alt Text](https://github.com/sleebapaul/hello_tensorflow/blob/master/images/simple_graph.jpg)

Now we'll code it using TensorFlow. 

In [16]:
# Graph

# b is a tensor of dimension 10 x 1 with all values as 1
b = tf.Variable(tf.ones((10, 1)))
# W is a tensor with random but uniformly distributed values between -1 and 1 on a dimension of 10 x 10. 
W = tf.Variable(tf.random_uniform((10, 10), -1, 1)) 
# x is a placeholder for a 10 x 1 tensor with type float32. 
x = tf.placeholder(tf.float32, (10, 1))
# calculating f using the above variables
f = tf.add(tf.matmul(W, x), b) # tf.matmul() performs matrix multiplication

# Session

import numpy as np
sess = tf.Session() # define session 
sess.run(tf.global_variables_initializer()) # initialize all the variable to be used
output = sess.run(f, feed_dict={x: np.random.random_sample((10, 1))}) # evaluating f by feeding the 
print(output)
print(output.shape)

[[ 2.24850464]
 [ 1.05696559]
 [-0.9978447 ]
 [ 0.38015342]
 [ 1.77992475]
 [ 1.84230733]
 [ 0.64847338]
 [ 0.40530998]
 [ 0.92679751]
 [ 0.78063881]]
(10, 1)


I think this is good enough to begin with TensorFlow. As we move along the learning path, we would be able to see a lot of cool stuff. I hope you enjoyed this joy ride. Thanks :) 